use_frameworks!

platform :ios, '9.0'

target 'CGTestTools_Example' do
  pod 'CGTestTools', :path => '../'

  target 'CGTestTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
